name: Build and test Docker images
on: [push, pull_request]

jobs:
  build-docker-images:
    name: build Docker images
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build web app
        run: |
          cd web-app
          docker build --no-cache -t web-app-4-containers-feature_not_bug:latest .
          docker run -d -p 5000:5000 web-app-4-containers-feature_not_bug

      - name: try contacting web-app with curl 
        run: |
          curl --request GET http://127.0.0.1:5000

      