name: Build and test Flask webapp
on: [push, pull_request]

jobs:
  build-pipenv:
    name: build and test with pipenv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
          working-directory: ./web-app

      - name: Regenerate lock file
        run: |
          pipenv lock
      - name: Install dependencies
        run: |
          pipenv install pytest pytest-flask
      - name: Test with pytest
        run: |
          pipenv run python -m pytest
    

      